### ISSUE TITLE
Warning: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by Lonnytunes** [makinacorpus/generated-hydrator-bundle#1]
https://github.com/makinacorpus/generated-hydrator-bundle/blob/e1de8fa5640922c6351869f88a7e7542a8595caa/src/HydrationPlan/ReflectionHydrationPlanBuilder.php#L188

In `findPropertyWithRawDocBlock()` method, line 251, `extractTypesFromDocBlock()` is supposed to return an array in any case. The `null` value is not supported.

Maybe the returned value should be an empty array instead?

Because I get an ErrorException for `Invalid argument supplied for foreach()` when a doc block associated with a property doesn't contain any `@var` attribute.

**Comment by pounard** [comment]
Yeah, that's what I'm going to do.
